### ISSUE TITLE
As a hacker, I want to be able to quickly help

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/frontend-ohack.dev#1]
New user, never used ohack Slack before
Go from ohack.dev to Slack, will need to create an account

As a hacker, the things I care about:
1. Find an interesting project
Language requirement? Tech stack
Already built?
Integrate with existing system?
Requirements?

2. Find a team
Is there a team already?

**Comment by gregv** [comment]
Need to finish this before the hackathon - first item is done in MVP form, still need to work through the second item

**Comment by ShallyBanh** [comment]
I might also add a section on preferred tech stack. There might be some folks who are looking to improve or learn certain language via the hackathon rather than optimizing for an interesting project

**Comment by gregv** [comment]
This one is ready to go for the hackathon - we have these GitHub Issues that are going to provide hackers/mentors with code pointers and more information
