### ISSUE TITLE
We need to know what someone's role is for OHack

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/frontend-ohack.dev#108]
We will have a bunch of hackers writing code for nonprofits, hopefully about 20 mentors (of various skill sets), nonprofits, and sponsors.

We need a way to figure out what role each person is playing so we can display it as a suffix to their slack profile to make it easy for people to know who they are.

In order to do this, we want to add a drop down to the profile page on OHack.dev to collect this.
![Screenshot_20230916-155459.png](https://github.com/opportunity-hack/frontend-ohack.dev/assets/6913307/714c0efa-f76e-4b2b-83f9-df7f64696bb6)

Options should be:
- Hacker (in school)
- Hacker (industry professional)

Mentor (software engineering)
- General software engineering
- Front-end (CSS/JS, Node, Angular, React, etc)
- Back-end (Java, Python, Ruby, etc)
- Mobile (iOS, Android)
- Data Science & Machine Learning
- DevOps: AWS, Google Cloud, Heroku
- GitHub 
Above should be multi-selectable

- Mentor (product manager)
- Mentor (UX/Design)
- Mentor (program management)
- Mentor (nonprofit mindset)
- Mentor (other)

Once saved this should POST to the /profile backend endpoint to save the data.
Data should be saved in firebase with a timestamp and a history (list of previous selections)

**Comment by rstackhouse** [comment]
@gregv, is there an API/model doc somewhere?

What is the component/file that needs to get modified here?

Per conversations elsewhere, should role, especially for more experienced (*cough* old *cough*) folks be implemented as a tag cloud?
