### ISSUE TITLE
Display the skillsets and programming languages required for a problem

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/frontend-ohack.dev#11]
Slack Channel: [#ohack-dev-skillsets](https://opportunity-hack.slack.com/archives/C048NQ8TS2K)

# Summary 
For some projects that already have a code base, we want to display what technology knowledge may be needed to develop it.

This is what a project currently looks like:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/6913307/199392891-1518da4c-f356-4d9d-a5b6-3a0a13098f9e.png">

It lacks the ability to call out specific skills and programming languages that are needed, for instance:
1. Software Engineering
 - Frontend: NodeJS/React
 - Backend: Python/Flask
2. UX
 - Help with mocking this out using something like Miro or Figma

# Code Pointers
The [nonprofit page](https://github.com/opportunity-hack/frontend-ohack.dev/blob/main/src/pages/nonprofit/%5Bnonprofit_id%5D.js#L308) with the `<ProblemStatement>` component is likely the targeted area for this change, somewhere around the [Needs Help](https://github.com/opportunity-hack/frontend-ohack.dev/blob/c3ac94d1455c0a881d20d3f24a800ee1ff6105f8/src/components/problem-statement.js#L228) chip

# Details
- Display the type of languages (e.g. JavaScript) or frameworks (eg. React)
- Add the deployment status (where the code is running and if it's currently online or offline)

**Comment by jotpowers** [comment]
I would also include deployment status.

**Comment by webbdays** [comment]
Ui to display the component was done.
 skill-set component pr #25

**Comment by gregv** [comment]
> Ui to display the SkillSet was done. skill-set component pr #25

Thank you @webbdays - it doesn't look like you submitted this project during the hackathon on DevPost https://opportunity-hack-2022.devpost.com/

**Comment by gregv** [comment]
![image](https://user-images.githubusercontent.com/6913307/210389638-9c504e3e-71cf-405d-97e8-08cb4771899e.png)
This is live now! Closing
