### ISSUE TITLE
Self-Service Corporate Hackathons

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/frontend-ohack.dev#12]
Slack Channel: [#ohack-dev-corporate-hackathons](https://opportunity-hack.slack.com/archives/C04A2JFD6MP)

Tell us you want to help by logging in and clicking "I want to help" [here](https://ohack.dev/project/8255742675e211ed9188ee89c326ccdb)

# Summary
As one of the most important visions for the future, we need to provide a way for a corporation to conduct their own Tech for Good nonprofit hackathon with the Opportunity Hack brand and process so that we might obtain a substantial donation to either help them run the hackathon or for providing them the tools and resources for the hackathon to be executed completely by that company.

We do [have an MVP runbook](https://opportunity-hack.github.io/Runbook/docs/) that details out most of the process around Opportunity Hack, but we need to build something that allows people to directly ask us for hackathon support on behalf of their company.

# More details
This likely will manifest into some kind of form on ohack.dev to start the process, the form might have details such as:
- Target nonprofits? (e.g. Animals)
- Dates?
- Logo? Ask for their company logo so we can go-brand and market with it
- Hackers: who will write the code to support nonprofits?
  - Employees or University or both
- Open to public or closed?
- Needs mentors?
  - What kind of expertise? (e.g. Python, React, Backend, DB)
- Has judges? (# depends on number of expected hackers)
- Shirt vendor?
- Work on generating new ideas to problems or completing projects?

**Comment by jotpowers** [comment]
1. What is our goal here that can't be accomplished with a google form?
2. I think the top level should include:
- What is the purpose of the hackathon?  (e.g. community engagement, employee engagement, recruiting)
- Is there a theme? (e.g. Financial Inclusion, Technical Literacy)
- What are the desired outcomes? (e.g. Code implemented and live supporting NPOs, robust college pipeline)

**Comment by gregv** [comment]
> 1. What is our goal here that can't be accomplished with a google form?

Gathering funds is probably the most important thing. We want to establish a vaulted card early in the process to removal all possible friction for any future work, or any subscription-based donation we may obtain
