### ISSUE TITLE
🏆Update our UX

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/frontend-ohack.dev#13]
Champion: @vertex 
Channel: [#ohack-dev-update-our-ux ](https://opportunity-hack.slack.com/archives/C04C5083NTV)

Tell us you want to help by logging in and clicking "I want to help" [here](https://ohack.dev/project/32429bda75e211ed9188ee89c326ccdb)

# Summary
Our UX for ohack.dev is in an infant form.  The text sizes aren't the same size, our color palette is not uniform, our buttons have too many styles...you get the idea.

We actually took this frontend from Auth0 as it made it easier to implement some of the core authentication strategies that we needed to fundamentally make ohack.dev secure.

Update our UX in anyway that you want, anything is fair game!

# More Details
- Here's a walkthrough of how to setup our frontend code with [GitHub Codespaces](https://youtu.be/AwSPRwRhylA)
- This is where it started from: https://github.com/auth0-developer-hub/spa_react_javascript_hello-world
- We have used [Material UI](https://mui.com/material-ui/) for most of the components you see today
- This is where we're at now ![image](https://user-images.githubusercontent.com/6913307/201700467-42f2a474-5e48-4668-bb72-71e3b24d78e8.png)

**Comment by mmbell21** [comment]
Anything that would be most helpful to you guys? I was thinking of doing a style guide and/or design system, but if there's anything else that would be helpful I can do that. (i.e. user testing, redesigns of some wireframes, etc.) 

Also a Miro of your UX aspirations was mentioned on Slack. Could you provide a link to that?

**Comment by gregv** [comment]
> Anything that would be most helpful to you guys? I was thinking of doing a style guide and/or design system, but if there's anything else that would be helpful I can do that. (i.e. user testing, redesigns of some wireframes, etc.) 
> 
> Also a Miro of your UX aspirations was mentioned on Slack. Could you provide a link to that?

[Here's a link to our Miro board](https://miro.com/app/board/uXjVOx7t63E=/?share_link_id=980282337036) @mmbell21 

Unfortunately we lack UX experience, so we don't have a style guide or design system. We actually borrowed ohack.dev from an Auth0 starter project.

You have artistic license to pitch anything you think would move us in the right direction 🙏

**Comment by danielyuenhx** [comment]
Hi, is this still available for the hackathon?

**Comment by gregv** [comment]
> Hi, is this still available for the hackathon?

@danielyuenhx - all projects are available!

**Comment by gregv** [comment]
I wanted to add a screenshot of ohack.dev here for posterity! It looks amazing!
![image](https://user-images.githubusercontent.com/6913307/213763275-dee0639a-1da8-4624-9e4e-b672f45c00d7.png)

**Comment by gregv** [comment]
👏 Officially closing this one out! 👏
ohack.dev is more beautiful because of you!

![068781c4d1ac11edae1facde48001122](https://user-images.githubusercontent.com/6913307/231050083-1a5e9835-d7d4-42f4-a534-186be3205b81.png)

![02db8f3ed1ac11edae1facde48001122](https://user-images.githubusercontent.com/6913307/231050089-1c7926c4-6c93-494d-830b-b54676ac5f8a.png)
