### ISSUE TITLE
Social links don't work

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/frontend-ohack.dev#153]
Links just bring you back to ohack.dev 

[Slack Message](https://opportunity-hack.slack.com/archives/C044RMJJPEW/p1707560533298359)

Code pointer https://github.com/opportunity-hack/frontend-ohack.dev/blob/7687129fc23e03e29f02466abaa1d3c962bce0f7/src/components/Footer/Footer.js#L45C16-L45C24

**Comment by rstackhouse** [comment]
@gregv, pretty sure you fixed this.

**Comment by gregv** [comment]
Still not fixed on mobile @rstackhouse
