### ISSUE TITLE
☀️Migrate OHack’s backend (api.ohack.dev) to fly.io 

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/frontend-ohack.dev#165]
Our frontend is running on Vercel, which is great for speed and other reasons and our backend is running on Heroku, which is expensive and not performant.

We’ve been using Fly.io for other projects and love it - we hope you will too!

Take a peek at this [Fly Config](https://github.com/opportunity-hack/evs/blob/dev/fly.toml) for our EVS project to get an idea of what you’ll need to do.

You can do this with our test backend first, https://test.api.ohack.dev/api/messages/public and then we’ll move things over to production after we test that.

**Comment by AndrewHUNGNguyen** [comment]
Hi @gregv. This is Andrew Nguyen, the person who reached out to you on Slack for details on this issue. Feel free to assign this issue to me.

**Comment by gregv** [comment]
Migration completed by @AndrewHUNGNguyen 👏  - updated DNS and we should be using Fly.io backend servers for both test.ohack.dev (staging) and ohack.dev (prod) in the next few hours! cc: @nemathew @jotpowers 

![image](https://github.com/opportunity-hack/frontend-ohack.dev/assets/6913307/ec31a7f7-90e1-475b-b702-c07bbeb992d6)
<img width="692" alt="image" src="https://github.com/opportunity-hack/frontend-ohack.dev/assets/6913307/5f78ce0f-f6d4-4ad7-ba2a-401f3351273a">

**Comment by gregv** [comment]
This one is done! We've been running with a Fly.io backend for 2 weeks
