### ISSUE TITLE
☀️ 👯‍♀️ Nonprofits without any projects - ask people to go to /nonprofits/apply

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/frontend-ohack.dev#184]
This has a "good first thing" label because this is a pretty straight-forward frontend change.

We have an opportunity to capitalize on people searching on Google.
<img width="1058" alt="image" src="https://github.com/user-attachments/assets/23e4f007-8e5e-4cc2-82ef-bc962f3dce24">
As you can see above, we have some impressions, but no clicks.  If we do have clicks to various pages, specifically for nonprofits without any projects yet, we want to ask folks (either someone familiar with the nonprofit or the nonprofit themselves) to give us what problems we might be able to help with.

Here's an example - if anyone lands on https://www.ohack.dev/nonprofit/8d785de2077811edbfdeb29c4ac23549 (a nonprofit we have worked with in the past, but we haven't added any specific details since it was ~5+ years ago before this website existed) - they won't see anything - just that there are no projects.
<img width="1179" alt="image" src="https://github.com/user-attachments/assets/2ad1dea0-6cf1-4fa4-9810-11e2e3043bf2">

If someone lands on a page with zero projects, we want to direct them to send us their projects over at https://www.ohack.dev/nonprofits/apply

This is likely a button on the page with some text that would encourage people to go to `/nonprofits/apply` if there's any thoughts they have on how we can help.

**Comment by CobyW98** [comment]
Added a pull request!

**Comment by gregv** [comment]
@CobyW98 - I've added a little more customization in 8599a432e9b1da5c58d3eb9f1fa0b2de8356f403 just so you can see how I've taken what you've done and added some A/B Testing to it

We're good to go! Closing this one
