### ISSUE TITLE
Hackathon Event Timeline Component

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/frontend-ohack.dev#193]
## Overview
We need to create an interactive timeline component for our hackathon event page. This timeline should display all events, highlight the current time, and dynamically adjust its view based on proximity to upcoming events.

https://github.com/user-attachments/assets/614ecb34-4389-4c91-89df-5ccdffe2a3d1

We want something that resembles this:
![image](https://github.com/user-attachments/assets/131b5eb5-e81c-4aab-a6ab-4ed83d8046a2)
Here's an example codebase: https://github.com/gregv/meeting-timeline that does something similar, but is meant for meetings, not for an event timeline that can adapt to 2 months away from first event, 1 month away, 2 weeks away, 1 week away, day of - we need a timeline that can zoom out and in to account for longer timelines.

The current timeline gets to be very busy when there are many things on it - here's the one for the ASU 2024 hackathon in October https://www.ohack.dev/hack/2024_fall
<img width="1208" alt="image" src="https://github.com/user-attachments/assets/87af402a-73d2-4a93-ae63-7a443ce6b2a1">

See an example of what we're trying to build here: https://gist.github.com/gregv/09319781377c12ab3947409d62b741fd

### Timeline Display
- [ ] Create a horizontal timeline showing all hackathon events
- [ ] Events should be represented by nodes on the timeline
- [ ] Each node should display the event name and time on hover
- [ ] Past events should be grayed out and moved to a separate timeline below the main one

### Current Time Indicator
- [ ] Show a glowing red circle indicating the current time on the timeline
- [ ] Display the current time above this indicator

### Dynamic Zooming
- [ ] Implement automatic zooming based on proximity to the next event:
  - If the next event is more than a month away, zoom out to show a broad view
  - If within 2 weeks, zoom to show all upcoming events
  - If within 1 day, zoom in to show detailed view of imminent events
- [ ] Allow manual zooming with '+' and '-' buttons

### Interactivity
- [ ] Enable panning of the timeline
- [ ] On hover over an event node, show a tooltip with event details

### Responsive Design
- [ ] Ensure the timeline fits within the width of the screen without horizontal scrolling
- [ ] Adjust layout for different screen sizes

## Technical Specifications
- Use PixiJS for rendering the timeline
- Use Moment.js for date/time calculations
- Implement as a reusable component
- Optimize for performance, especially when handling many events

## Data Structure
Events should be provided in the following format:
```json
{
  "description": "Event description",
  "name": "Event Name",
  "time": "2024-10-12T08:00:00-0700"
}

**Comment by gregv** [comment]
This can be run all standalone, so marking this as a good first thing - and it's basically all front-end

**Comment by rohitt-gupta** [comment]
Alright @gregv ,
is this open to work? I want to try it out.
Thanks for providing the video attached, helped a lot to understand the problem statement.
Also sometimes, i might need a little bit of help/guidance.

assign it to me, i will check the rest.

**Comment by gregv** [comment]
Yes @rohitt-gupta 🚀!

**Comment by gregv** [comment]
@rohitt-gupta - we didn't hear back from you, but we've made these updates where we no longer need this issue

![image](https://github.com/user-attachments/assets/60ed18d4-1296-4a4f-8e5d-c22b2abd9967)
