### ISSUE TITLE
Cash Prize Bounty

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/frontend-ohack.dev#5]
Slack Channel: [#ohack-dev-cash-prize-bounty](https://opportunity-hack.slack.com/archives/C045AFHH3FH)

Tell us you want to help by logging in and clicking "I want to help" [here](https://ohack.dev/project/9652722241ca11edb6d8b29c4ac23549)

# Summary
Our hackathons have matured over the course of several years, originally giving out all prize money on the day of the hackathon to everyone who won. 

Later, we realized that in order to complete projects to help nonprofits, it would be advantageous to give 80% of the prize when teams complete their objective and the non-profit has signed off on it. This worked well, where about two out of three projects would get paid out for completing their objective.

We want to take the next step forward, creating a crowdsourced alternative to funding the completion of projects. Think of this as a mixture of GoFundMe, UpWork, Susan G Komen, and CatchAFire. After a team has won a hackathon prize, we want to allow them to seek funding for completion of their project. 

# Code Pointers 

# More Details
1. Anyone should be able to share a link directly to that project to ask for funding
2. Anyone should be able to contribute to the project by donating money, either one time or on a recurring basis until the project is completed
3. When the project is completed and signed off by a nonprofit, 80% of the prize money goes to the hacking team, and 20% goes to the mentors who were supporting them.
4. Any money donated needs to be earmarked to only serve the purpose of prize money for this specific project. 
5. When someone shares the link on social media it should be attention grabbing and content rich so that we can incentivize people to donate.
6. If a corporation decides to donate, we want to give them the ability to upload a logo so that they can prominently display it for that project and on ohack.dev. 
7. All data associated with donors and projects should be stored in a database that is timestamped for future reporting.

**Comment by jotpowers** [comment]
I know we talked some about this.  Perhaps think about this as donations to the NPO?

**Comment by gregv** [comment]
> I know we talked some about this. Perhaps think about this as donations to the NPO?

Yeah, good reminder - we'd want that breakdown for prize payout to be ideally distributed to the NPO + Hackers + Mentors based on some opt-in/out status from mentors/hackers, but to start a blanket 10% goes to NPOs, then 70% to hackers, 20% to mentors (as an MVP).

**Comment by jotpowers** [comment]
I was wondering if it instead made sense to have the donation be directly to the NPO, and then the NPO pays out the mentors/hackers.  That way the sales pitch is way easier "I'm doing a project for Illiterate Starving Kittens in Africa, and if you donate to them mentioning this project it will really help the project move along!" 

It also removes us from the middle, but I'm not sure if that's a good or bad thing.

**Comment by gregv** [comment]
> I was wondering if it instead made sense to have the donation be directly to the NPO, and then the NPO pays out the mentors/hackers.  That way the sales pitch is way easier "I'm doing a project for Illiterate Starving Kittens in Africa, and if you donate to them mentioning this project it will really help the project move along!" 
> 
> It also removes us from the middle, but I'm not sure if that's a good or bad thing.

I think removing us completely is likely not what we want. If too we add too much on the nonprofits to payout, some may be too slow and struggle with paperwork - we would like to end on a good note with everyone almost immediately when the project is finalized. They do have the daily staff that we don't, but I think it takes away from their core mission to pay out hackers who finished a project for them.

We also stand to gain something in next steps with the hacking team if Opportunity Hack is the payer (maybe we add a multiplier if they work on another project after completing one)
