### ISSUE TITLE
Help people find interesting projects

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/frontend-ohack.dev#6]
Slack Channel: [#ohack-dev-help-people-find-interesting-projects](https://opportunity-hack.slack.com/archives/C046EP1JT5W)

Tell us you want to help by logging in and clicking "I want to help" [here](https://ohack.dev/project/c4097994476b11eda895827f9c97b805)

# Summary
One of the things ohack.dev lacks is the ability for people to discover projects that they may want to work on.  We don't currently have any features for filtering or searching outside of these two buttons that allow for "Needs Help" or "Live" projects to be displayed.  We want to enhance this functionality so that people can more quickly find a passion project they can either mentor or hack for.
<img width="874" alt="image" src="https://user-images.githubusercontent.com/6913307/199401392-65622311-a8e3-4743-9e58-1490da8b41a2.png">

Platforms like Catchafire.org have this way of illustrating their projects:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/6913307/199401492-7249a92d-e6af-4c7b-9dd3-b2a55da4dc22.png">

# More details
- DONE: Quick filtering functionality to allow people to quickly find a project they can help with 
- DONE: llow for mentors and hackers to self-service and join projects
- ALMOST DONE (need to add skill area to search): Search capability, allow for searching by full text, or by skill area, or by effort required, etc.
- Profile match based on skill (e.g. Python projects, etc.)
- It might make sense to introduce a profile ability to capture interests from someone and then use those to rank the results of the projects
- Match based on impact area (e.g. Students, Medical, Animals, etc.) and impact of solution (eg. 100 people)
- Favor projects that aren’t yet full (5 hackers, 5 mentors)
- Solves the “I want to help, but there are no hackathons coming up” problem - allow people to self-service and find projects they can start hacking or mentoring for today, so they don't have to wait for a hackathon.
- Solves the “I work for ESPN and want to help a nonprofit” problem - this allows potential sponsors to self-service and find interesting projects for their employees to work on as part of an internal hackathon.

**Comment by victoriaamoroso** [comment]
@gregv I'm a UX Designer and Researcher. I'm interested in helping and/or being a "floater" mentor for multiple items that need UX! One of my initial questions -- is there anyone we can talk to to understand the current process of how they find/become involved with the project so that we can identify pain points? I'm fairly new, but if there is also a step by step workflow of how mentors and hackers currently join projects that would be great or I can help visualize it.

**Comment by gregv** [comment]
Hey @victoriaamoroso! 🥳 
> I'm interested in helping and/or being a "floater" mentor for multiple items that need UX!
That would be incredible!

> One of my initial questions -- is there anyone we can talk to to understand the current process of how they find/become involved with the project so that we can identify pain points
I don't see that we've detailed this out in https://opportunity-hack.github.io/Runbook/docs/ @jotpowers - I'll check our other docs to see if we have something more substantial

>  I'm fairly new, but if there is also a step by step workflow of how mentors and hackers currently join projects that would be great or I can help visualize it.
You got it! We'll work on documenting this in the next few days

**Comment by gregv** [comment]
Hey @victoriaamoroso - [here's a link to our Miro board](https://miro.com/app/board/uXjVOx7t63E=/?share_link_id=980282337036) that should hopefully help: 

Right [here](https://miro.com/app/board/uXjVOx7t63E=/?moveToWidget=3458764539091718147&cot=14) is our flow diagram.

On the UX side, we have some very basic wireframes of what we're hoping to build for ohack.dev [here](https://miro.com/app/board/uXjVOx7t63E=/?moveToWidget=3458764526589934483&cot=14).

**Comment by gregv** [comment]
![image](https://user-images.githubusercontent.com/6913307/234043496-bba8bc2a-c38f-439c-b211-4e76ab70a392.png)
New update from @danielyuenhx going live today
