### ISSUE TITLE
🏆 Enable Other Volunteer Opportunities

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/frontend-ohack.dev#9]
Slack Channel: [#ohack-dev-enable-other-volunteer-opportunities](https://opportunity-hack.slack.com/archives/C045R2M3R7U)

Tell us you want to help by logging in and clicking "I want to help" [here](https://ohack.dev/project/c84ff96e476c11eda895827f9c97b805)

# Summary
This one is slightly more open-ended.  The current system only allows for Hackers and Mentors, where both of these positions are software engineering focused.  We still want to encourage all people, regardless of their background to volunteer their time to help us.  We need you to build something into our ohack.dev platform that would allow for us to engage with volunteers who are looking to support us.  The ultimate goal is to collect some information about what they are looking for, onboard them into Slack, and give them autonomy to accomplish goals as discussed below.

These are the high-level areas where someone who isn't a software engineer can help us:
1. Source projects from nonprofits: reach out to nonprofits, explain OHack, funnel them into our (to be built in #10) nonprofit form and get them to join Slack.
2. Follow-up with nonprofits: We would like to have a pretty continual connection between OHack and the nonprofits we've worked with in the past, but we can't currently scale to do this effectively - ideally every month.  Volunteers here would reach out to nonprofits to see how their delivered solution is working for them, collect feedback, record demo videos of the product working for social media promotion, etc.
3. Recruit sponsors to fund projects: Once #5 is built, we will need help in recruiting sponsors who are interested in OHack to either run their own hackathons with nonprofits/runbooks we provide, or we'll run the entire thing for them.  We'll need volunteers who can use SalesForce to reach out to potential sponsors on a continual basis and help with marketing.
4. Engage with previous hackers and mentors to get them to join: Volunteers can help us stay connected to our hacker, mentor, and judge community by keeping lines of communication open over the entire year.  As we plan to have more continual development on ohack.dev, we'll need to stay engaged with these groups of people and let them know when we need assistance - we'll also want to get their feedback to make OHack a better place.
5. Social media engagement:  We don't have much effort on this side as of today, a volunteer in this area can help us improve our social footprint and help with content and marketing/ads.
6. Send newsletter to Women in Tech, Out in Tech, etc.:  We need to both create a list of the various groups/clubs we want to target as hackers and mentors, and also actively engage with these communities to build our brand.
7. Slack engagement: A volunteer here can help to engage our Slack user community of over 1,000 people, to keep them engaged and involved within Slack.
8. Day Of Hackathon Volunteer: if a person just wants to volunteer for a specific hackathon and they can help with logistics, helping answer any questions from hackers + mentors and do comms (i.e lunch in 20mins, 30mins until hackathon is over, general announcements, etc) during the event via slack.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/6913307/199393983-e5552f6e-bef4-4ff3-8f8f-1c3a29d3f06a.png">

# Code Pointers
This would likely be another button on the main [index.js](https://github.com/opportunity-hack/frontend-ohack.dev/blob/c3ac94d1455c0a881d20d3f24a800ee1ff6105f8/src/pages/index.js#L15) and another page, likely /volunteer

**Comment by jotpowers** [comment]
Also just "Coordinator".  Someone to handle the logistics of food/snacks/volunteer schedules.

**Comment by gregv** [comment]
Love that idea @ShallyBanh - I'll update this Issue to talk more about that

**Comment by leonkoech** [comment]
In regards to Newsletters for change the following issues need to be addressed. The list is still [WIP⚠️]

1. Some front-end components need to be created. These components should be the contents of the header and the footer. My idea of the two would be having a logo at the top center the message and a footer with grey texts with the details about opportunity hack and an unsubscrbe button(The functionalities are complete already, it's now the front end)
### ISSUE 1: 
The UI for this has to be drawn and presented to the group. Attention to detail is key :) 

1 a) Because of this we need some components, in html and css (bonus if you can play around with responsiveness). The two components would be;
### ISSUE 2:
 the header component that houses the icon 
 ### ISSUE 3:
 footer component that houses details about opportunity hack and the unsubscribe button

**Comment by leonkoech** [comment]
![Screenshot 2023-01-25 223040](https://user-images.githubusercontent.com/39020723/214758848-9c7ccbf3-2ac8-43b9-a66b-91d341ac39c2.png)

Concept Image as to how a template should look :)

**Comment by leonkoech** [comment]
Unsubscribe will be added dat the bottom

**Comment by leonkoech** [comment]
2a. Naming conventions are off. This more so has to do with the class names for the front end
2b. we need a better front end for the newsletters page. You can play around with css on this one

**Comment by leonkoech** [comment]
# ISSUE 6:
Backend: 
Separate email template styles from the template file. Instead, think of creating an scss/CSS file and scanning it through python. OR better yet, have an API that brings the scss/css file contents from the front end, thereby fully separating the front end and the backend logic

**Comment by leonkoech** [comment]
# ISSUE 6:
Backend:
Separate email template styles from the template file. Instead, think of creating an scss/CSS file and scanning it through python. OR better yet, have an API that posts the scss/css file contents from the front end, thereby fully separating the front end and the backend logic

**Comment by leonkoech** [comment]
# ISSUE 7
Front End 
When API hasn't received a boolean as to whether all emails were sent, show a loading screen

**Comment by leonkoech** [comment]
# FEATURE 1
To cover issue 7 above the following component will be created 

## A loading page 

or a component with a loading gif/rotating circle in the middle. 

```<div class="parent">
     <CircleSpinningComponent></CircleSpinningComponent>
     </div>
```

then in scss something like; 
``` .parent{
       width: 100vw;
       height: 100vw;
       position: fixed;
       display: flex;
       justify-content: center;
       align-items: center;
       z-index: 10;
       // you'll have to confirm the highest z-index based on component arrangement when testing or searching for it in vs code)
       }
```
then make the component render on condition. The boolean should be a prop.

**Comment by leonkoech** [comment]
# FEATURE 2
this will be a bit heavy but manageable + I can help along the way
Creating a form to make adding a button and or image be straightfoward. Prompting the user after they click on an 'add custom ohack component' button, to select a text, a link and type of button or image.

**Comment by leonkoech** [comment]
# FRONT-END FINAL MOCKUP
![IMG_3261](https://user-images.githubusercontent.com/39020723/215622608-b7db256c-a241-416f-8f75-9819bb000c55.JPEG)

In my head, this is how the final design for the newsletter editing page should be. The higher the number the closer it is to "nice to haves", the lesser the number the either least amount of time and/or effort required to complete it.
